### ISSUE TITLE
ts reloads deleted contacts

### ISSUE THREAD

**Issue by DasMonschta** [DerLuemmel/Contact-Cleaner#1]
Somehow Teamspeak reloads the deleted contacts when you restart the client. @Bluscream

**Comment by Bluscream** [comment]
was meinst du?

---
Hast du mal meine version angesehen? https://github.com/Bluscream/pyTSon_plugins/tree/master/scripts/purgeContacts (nie beendet) :D

**Comment by DasMonschta** [comment]
ich lösche die einträge aus der db aber nach einem ts neustart sind sie wieder da

**Comment by Bluscream** [comment]
KP, könnte sein das er die DB im RAM hat und beim beenden ausm RAM speichert. Was auch sein könnte ist das du nachm `deleten` der einträge nochmal speichern musst? kp wie gesagt :D

**Comment by DasMonschta** [comment]
wenn ich es so mache dass der ts crasht, dann bleiben die gelöschten einträge auch gelöscht.

also muss da irgendeine routine beim beenden des clients für sorgen dass wie du sagtest die daten ausm cache oder so geholt werden

**Comment by DasMonschta** [comment]
haha hab eine freche geniale Lösung.

Ich schließe (crashe höhö) den client nach dem DELETE einfach mit `qFatal("badaboom")`

So holt er sich die Daten nicht zurück.

Dann steht halt auf dem "Clean"-Butten nicht mehr clean sondern "Clean & Close Teamspeak"

**Comment by Bluscream** [comment]
lol
